services:
  - docker      
script:
  - docker image build -t dfleming97/imagetest .
deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push dfleming97/imagetest
